type = "elasticsearch"
version = "7.10.1"
cpu = 200
ram = 4000
password = "{{PASSWORD_ES}}"

[[nodeSets]] # https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-node-configuration.html
name = "epzp"
count = 1

[inputs]
PASSWORD_ES.type = "secret"
